# Path to your Oh My Zsh installation.
export ZSH="$HOME/.config/ohmyzsh"
export ZSH_COMPDUMP="$ZSH/cache/completions/.zcompdump-$HOST"
ZSH_THEME="owntheme"  # set to random to iterate among list below
# ZSH_THEME_GIT_PROMPT_PREFIX=" %{$fg[white]%}("
# ZSH_THEME_GIT_PROMPT_SUFFIX=")%{$reset_color%}"
# ZSH_THEME_GIT_PROMPT_DIRTY="*"
# ZSH_THEME_GIT_PROMPT_CLEAN=""
ZSH_THEME_RANDOM_CANDIDATES=( 
#  "essembeh"  # simple one-liner  "macovsky"  # simple one-liner
#  "candy"  # 2-line, time  "bira"  # 2-line, no time
  "3den"
)

# Uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
zstyle ':omz:update' mode reminder  # just remind me to update when it's time
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"
# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# vi-mode settings
VI_MODE_RESET_PROMPT_ON_MODE_CHANGE=true
VI_MODE_SET_CURSOR=false
# timer settings
TIMER_PRECISION=1
TIMER_FORMAT='\n[%d]'
TIMER_THRESHOLD=0.5

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=

plugins=( git vi-mode timer pixi-env )
source $ZSH/oh-my-zsh.sh
INSERT_MODE_INDICATOR="%{$fg[yellow]%} 󰫶 %{$reset_color%}"
MODE_INDICATOR="%{$fg[blue]%} 󰫻 %{$reset_color%}"
PROMPT="$PROMPT\$(vi_mode_prompt_info) "
RPROMPT=""

# export LANG=en_US.UTF-8
#LS_COLORS='ln=1;4:ex=0;4:ow=0:mi=0:so=0'
#export LS_COLORS
# cmp opts
zstyle ':completion:*' menu select # tab opens cmp menu
zstyle ':completion:*' special-dirs true # force . and .. to show in cmp menu

# For a full list of active aliases, run `alias`.
# maybe move to $ZSH_CUSTOM/aliases.zsh
if (( $+commands[lxxxsd] )); then
  alias ls='lsd --color=auto --hyperlink=auto --group-directories-first'
else
  alias l='ls -hAl --group-directories-first --color=auto'
  alias ls='ls --color=auto --hyperlink=auto --group-directories-first'
  alias ls_string='ls -mQ --color=auto --group-directories-first'
fi
alias job='ps -ef | grep frivas1'
alias tail='tail -n 20'
alias grep='grep --color=auto'
# arch update mirror list
alias update_mirrors='sudo reflector --protocol https --verbose --latest 25 --sort rate --save /etc/pacman.d/mirrorlist'
alias v='nvim'
alias vi='nvim'
alias vim='nvim'

alias runwebui="sudo systemctl start docker && sudo docker start -i -a open-webui"

export OLLAMA_MODELS=/home/fdo/.ollama/models
export OLLAMA_HOST=127.0.0.1:8090
export PATH="$PATH:/home/fdo/.pixi/bin"
export DOTDROP_CONFIG=/home/fdo/dotfiles/dotdrop.config
export DOTDROP_PROFILE=kde_desktop
export EDITOR=nvim

# hook to kickstart pixi shells with fastfetch and others
# these apps clog the init for pixi enough to avoid sourcing it
function pixi_hook(){
  eval "$(pixi shell-hook)"
}
# edit pixi env config to not alter ps1
function pixi_trim_ps1(){
  pixi config set shell.change-ps1 false
}
# change image for fastfetch
function fastfetch_switch_waifu(){
  # defaults to sfw/neko
  kind=${1:-sfw}
  repo=${2:-neko}
  source ~/.config/fastfetch/change_waifu.sh $kind $repo
}
# yazi start with 'y' and change dir when quitting
function y() {
	local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
	yazi "$@" --cwd-file="$tmp"
	if cwd="$(command cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
		builtin cd -- "$cwd"
	fi
	rm -f -- "$tmp"
}




